app = 'quenta-ex'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[env]
  PHX_SERVER = 'true'
  PHX_HOST = 'ex.quenta.dev'
